[package]
name = "commandor"
version = "0.1.0"
description = "CLI commands manager"
keywords = ["cli"]
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/krypt0nn/commandor"
edition = "2021"
